### PR TITLE
feat(iv): connect identity vault for a total auth solution

### PR DESCRIPTION
**Pull request by eric-horodyski**

### CODE REVIEW

**Comment by kensodemann** [comment]
Testing on my iPad, I get the following incorrect behaviors:

**No Navigation After Login**

1. Use any type of session locking
2. Log in
3. Control returns to login page, but app never redirects into app, even though log in worked

**Note:** If using Device or Session PIN locking, you can shutdown the app and restart it. When unlocking you will be redirected into the app. If you put the app in the background, though, it behaves like it is not logged in until you shutdown and restart.

**Note:** Playing with the app, this behavior seemed to clear itself up at some point. Certainly weird.

**Secure Storage Asks to Unlock**

1. Leave default of "Never Lock Session"
2. Log in
3. Shut down
4. Upon restart the Unlock pages shows but you cannot really unlock the app.

**Weird Behaviour Switching Modes**

1. Use Session PIN locking
2. Log in and do what you need to in order to get in to the app (see first bug)
3. Log out
4. Use Device Security
5. Log in
6. When returning to the login screen, you will need to enter the previous session PIN before continuing.

**Comment by eric-horodyski** [comment]
@kensodemann - When you have some free time, mind smoke testing? I've resolved all the issues, albeit the user will be prompted to unlock on app launch if authenticated.

**Comment by kensodemann** [comment]
Smoke testing...

image

**Review by kensodemann — APPROVED** [review]
Tested and worked fine for me.

**Comment by eric-horodyski** [comment]
Merged, but keeping branch around as it is referenced in an internal ticket at the moment.

**Pull request merged**
